### ISSUE TITLE
Returning Warning message: Standard deviation is zero in ccm() function

### ISSUE THREAD

**Issue by bruno-soares** [ha0ye/rEDM#17]
Trying to apply ccm() function in two temporal series of abundance data of fish species and the function returns the following warning message: 
In (function (x, y = NULL, use = "everything", method = c("pearson",  :
  standard deviation is zero

Why am I getting this warning? How can I solve it?

**Comment by ha0ye** [comment]
If your time series has a lot of repeated values, then some of the metrics may return an NA because there's no variance in the observed values for the predicted variable.
