### ISSUE TITLE
Package cannot be loaded in Windows with Chinese system language

### ISSUE THREAD

**Issue by Sciurus365** [ha0ye/rEDM#19]
Hello,
I tried to use rEDM in Windows but it couldn't be loaded. After several tryings, I found when I switch the system language from Chinese to English, the problem can be solved. So I think there might be some encoding problems in the package. Could you check with this? Thanks.

**Comment by ha0ye** [comment]
I don't have a system to test on, so it won't be feasible for me to see where the issue is. Maybe try doing an install without building vignettes to see if that fixes the issue? There might be some encoding around the vignettes and references that is causing the problem. Other than that, I don't really have any useful suggestions.

**Comment by Sciurus365** [comment]
> I don't have a system to test on, so it won't be feasible for me to see where the issue is. Maybe try doing an install without building vignettes to see if that fixes the issue? There might be some encoding around the vignettes and references that is causing the problem. Other than that, I don't really have any useful suggestions.

I just tried and this can work. Many thanks!

**Comment by Sciurus365** [comment]
> I don't have a system to test on, so it won't be feasible for me to see where the issue is. Maybe try doing an install without building vignettes to see if that fixes the issue? There might be some encoding around the vignettes and references that is causing the problem. Other than that, I don't really have any useful suggestions.

A follow-up to this: I found this can only solve the problem with the Chinese system language, but not with the Chinese region setting. So if I install it with vignettes, both the system language and the region setting should be English to make it work; if I install it without vignettes, the system language can be Chinese, but the region setting still needs to be English. I guess there are still some other encoding-related problems in the package.

**Comment by ha0ye** [comment]
> > I don't have a system to test on, so it won't be feasible for me to see where the issue is. Maybe try doing an install without building vignettes to see if that fixes the issue? There might be some encoding around the vignettes and references that is causing the problem. Other than that, I don't really have any useful suggestions.
> 
> A follow-up to this: I found this can only solve the problem with the Chinese system language, but not with the Chinese region setting. So if I install it with vignettes, both the system language and the region setting should be English to make it work; if I install it without vignettes, the system language can be Chinese, but the region setting still needs to be English. I guess there are still some other encoding-related problems in the package.

Hmm, do you have the same issue (region setting needs to be English) with other packages installed via github?

**Comment by Sciurus365** [comment]
> > > I don't have a system to test on, so it won't be feasible for me to see where the issue is. Maybe try doing an install without building vignettes to see if that fixes the issue? There might be some encoding around the vignettes and references that is causing the problem. Other than that, I don't really have any useful suggestions.
> > 
> > 
> > A follow-up to this: I found this can only solve the problem with the Chinese system language, but not with the Chinese region setting. So if I install it with vignettes, both the system language and the region setting should be English to make it work; if I install it without vignettes, the system language can be Chinese, but the region setting still needs to be English. I guess there are still some other encoding-related problems in the package.
> 
> Hmm, do you have the same issue (region setting needs to be English) with other packages installed via github?

I installed that from CRAN actually, but other packages all work well (from either source). And installing it from github doesn't solve the problem.

**Comment by ha0ye** [comment]
Oh, if you’re using the version on CRAN, then that is the current stream with a different backend over at https://github.com/SugiharaLab/rEDM , so I urge you to post an issue for the devs there. This repo is for the legacy version and hasn’t been updated in 2 years.
