### ISSUE TITLE
Questions on identifying nonlinearity

### ISSUE THREAD

**Issue by luckyCindy** [ha0ye/rEDM#21]
Hello, anyone?
Before the CCM analysis, I met a question about the criteria of identifying nonlinearity.
As the follow figure showed, the best prediction skill was at θ=0.1, which was just a bit higher that the skill at θ=0.001, and the prediction skills began to decrease obviously after θ>0.1. 
![image](https://user-images.githubusercontent.com/113500679/190084117-a98d1ab7-6e3f-4faa-a2dd-f8bf45010d23.png)

Because the best θ was near to zero and the increased prediction skills was 0.002 as the θ ranged from 0 to 2, I wonder whether this result are enough robust to be considered as the nonlinearity. If not, do we need to create the surrogate data to further verify this?

**Comment by ha0ye** [comment]
This repository isn't really active anymore. I suggest you contact the developers at https://github.com/SugiharaLab/rEDM/

But to answer your question: with such a small improvement in prediction, I would generally not consider this evidence for nonlinearity. There are different sorts of thresholds that have been used previously, so you may want to check some of the examples in the literature. I think maybe Ushio et al. 2018 had one, as well as Chang et al. 2020 and 2022.
