### ISSUE TITLE
Is an overlap between lib and pred a problem?

### ISSUE THREAD

**Issue by Falnesio** [ha0ye/rEDM#7]
Reproducing the tutorial on some data I found this. Is it a problem? The next part of the tutorial seems to turn out fine (summary(output...)), just checking here to see if everything is ok.
```
Warning message:
In model$run() :
  Found overlap between lib and pred. Enabling cross-validation with exclusion radius = 0. 
```

**Comment by adamtclark** [comment]
Yes, that's fine. The package is just warning you that because the training and testing data overlap, it's automatically implementing cross validation (i.e. when predicting x(t = y), it doesn't include timestep t = y in the training data).
